@startuml general_algorithm
start
fork
if (observation function available?) then (yes)
else (no)
:real target environment]
note right
where:
- agents can be deployed, updated, removed
- actions and observations are defined
- traces can be collected
end note
:collect environment's traces;
:imitation learning;
endif
:observation function]
fork again
:objective description]
if (is the reward function available) then (no)
:o;
else (yes)
:e;
endif
end fork
stop
@enduml